version: '3.8'

services:
  orbitx-website:
    build: 
      context: https://github.com/AltusRossouw/Orbitx-Website-New.git
      dockerfile: Dockerfile
    container_name: orbitx-website
    ports:
      - "3330:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - PORT=3000
      - HOSTNAME=0.0.0.0
    volumes:
      - orbitx_data:/app/.next
      - orbitx_assets:/app/public
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=false"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  orbitx_data:
    driver: local
  orbitx_assets:
    driver: local
