version: '3.8'

services:
  orbitx-website:
    build: .
    container_name: orbitx-website
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    networks:
      - orbitx-network

networks:
  orbitx-network:
    driver: bridge
